baseURL: https://francesconicoli00.netlify.app/
languageCode: en-us
title: Personal Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      CHECK MY DATA SCIENCE PROJECTS
    title: Welcome to my Portfolio
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 81, Fieldgate Street, Tower House Flat 13
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: fnicoli.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 783 153 8798
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Francesco Nicolì
    enable: yes
#    quicklinks:
#      - alt: HTML5 UP
 #       text: 'Design: '
  #      url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
  #      label: Twitter
   #     url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nicoli.francesco.3/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/___fra00___/
      - icon: fa-github
        label: GitHub
        url: https://github.com/francesconicoli00
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/francesco-nicoli/
  image: ''
  name: Francesco Nicolì
  navigation:
    #button1:
     # - name: Get Started
      #  url: blogs/biography1
#    button2:
#      - name: Log In
#       url: '#'
    links:
      - name: Home
        url: '#'
      #- name: Blogs
      #  url: '#'
      - name: About Me
        url: blogs/biography1
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: Nicolì
    title: Francesco
  tiles:
    enable: yes
    showcase:
      
      - image: NLP_banner.jpg
        subtitle: NLP application on accounting data
        title: NLP-based cost synergy analysis (PY)
        url: docs/LondonLab_Final_Notebook.html
      - image: movie_banner.jpg
        subtitle: Predicting movie ratings using User comments
        title: Text Mining & Neural Network on Movie Data (R)
        url: docs/brexit_project.html
      - image: ensemble_algos.jpg
        subtitle: Predicting London House prices
        title: Regression with Ensemble algorithms (R)
        url: docs/ensemble_algorithms.html
      - image: BBC_project.jpg
        subtitle: BBC iPlayer customer segmentation
        title: Segmentation with Clustering algorithms (PY)
        url: docs/clustering_project_PY.html
      - image: advertising_banner.jpg
        title: The Power of Optimisation (PY)
        subtitle: Optimal Advertising strategy with Linear Programming
        url: docs/workshop1_francesco_nicoli.html
      - image: s&p500.jpg
        subtitle: Using SVM algorithm to forecast S&P500 Index
        title: Support Vector Machine for Finance (PY)
        url: blogs/support_vector_machine
      
      
      
  two:
    buttonText: About me
    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
    title: Do you want to know more about me?
    url: blogs/biography1
