baseURL: https://francesconicoli00.netlify.app/
languageCode: en-us
title: Personal portfolio website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      VISITING THIS WEBSITE, YOU WILL HAVE THE CHANCE TO KNOW
      A BIT MORE ABOUT ME. IN THE FOLLOWING SECTIONS YOU CAN FIND
      PERSONAL INFORMATION, PAST EXPERIENCES, PROFESSIONAL GOALS
      AND PROJECTS I'VE BEEN INVOLVED IN. ENJOY!
    title: Hi, my name is Francesco
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 71, Victoria Park Road E9 7NA
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: fnicoli.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 783 153 8798
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Francesco Nicolì
    enable: yes
#    quicklinks:
#      - alt: HTML5 UP
 #       text: 'Design: '
  #      url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
  #      label: Twitter
   #     url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nicoli.francesco.3/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/___fra00___/
      - icon: fa-github
        label: GitHub
        url: https://github.com/francesconicoli00
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/francesco-nicoli/
  image: ''
  name: Francesco Nicolì
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
#      - name: Log In
#       url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: Personal Portfolio
    title: Francesco
  tiles:
    enable: yes
    showcase:
      - image: sfgolden.jpg
        subtitle: A brief presentation
        title: About me
        url: blogs/biography1
      - image: Sailing_theme.jpg
        subtitle: My sailing experience
        title: Sailing
        url: blogs/sailing_1
      - image: piano_banner.jpg
        subtitle: My music experience
        title: Piano
        url: blogs/piano_1
      - image: linkedin_profile_photo.jpg
        subtitle: Explore my curriculum
        title: Business experience
        url: blogs/business_experience
      - image: thesis_banner.png
        subtitle: Explore my undergrad thesis
        title: My final thesis
        url: blogs/thesis_project
      - image: brexit_banner.png
        subtitle: Explore my analytics project
        title: Brexit vote analysis
        url: blogs/brexit_project
      
  two:
    buttonText: Get Started
    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
    title: Explore the blogs, get started!
    url: blogs
