baseURL: https://francesconicoli00.netlify.app/
languageCode: en-us
title: Personal portfolio website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      VISITING THIS WEBSITE, YOU WILL HAVE THE CHANCE TO TAKE A LOOK
      TO THE MOST INTERESTING DATA SCIENCE PROJECTS I HAVE BEEN INVOLVED IN,
      ALONG WITH A BRIEF PRESENTATION ABOUT MYSELF. ENJOY!
    title: DATA SCIENCE PORTFOLIO
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: 81, Fieldgate Street, Tower House Flat 13
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: fnicoli.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 783 153 8798
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Francesco Nicolì
    enable: yes
#    quicklinks:
#      - alt: HTML5 UP
 #       text: 'Design: '
  #      url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
  #      label: Twitter
   #     url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nicoli.francesco.3/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/___fra00___/
      - icon: fa-github
        label: GitHub
        url: https://github.com/francesconicoli00
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/francesco-nicoli/
  image: ''
  name: Francesco Nicolì
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
#      - name: Log In
#       url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: Personal Portfolio
    title: Francesco
  tiles:
    enable: yes
    showcase:
      - image: sfgolden.jpg
        subtitle: A brief presentation
        title: About me
        url: blogs/biography1
      - image: ensemble_algos.jpg
        subtitle: Predicting London House prices
        title: Ensemble Machine Learning with R
        url: blogs/ensemble_algorithms
      - image: python_code.jpeg
        title: Linear Programming with Python
        subtitle: Optimal Advertising strategy with Linear Programming
        url: blogs/linear_programming
      - image: s&p500.jpg
        subtitle: Using SVM algorithm to forecast S&P500 Index 
        title: Support Vector Machine implementation with Python
        url: blogs/support_vector_machine
      - image: thesis_banner.png
        subtitle: Explore the content of my undergraduate thesis
        title: Final undergraduate thesis
        url: blogs/thesis_project
      - image: movie_banner.jpg
        subtitle: TM Analysis & ANN Fit on Movie Data
        title: Text Mining & Neural Net on Movie Data
        url: blogs/ml_final_project
      
  two:
    buttonText: Get Started
    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
    title: Explore the blogs, get started!
    url: blogs
