baseURL: https://francesconicoli00.netlify.app/
languageCode: en-us
title: Personal portfolio website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      VISITING THIS WEBSITE, YOU WILL HAVE THE CHANCE TO KNOW
      A BIT MORE ABOUT ME. IN THE FOLLOWING SECTIONS YOU CAN FIND
      PERSONAL INFORMATION, PAST EXPERIENCES, PROFESSIONAL GOALS
      AND PROJECTS I'VE BEEN INVOLVED IN. ENJOY!
    title: Hello, my name is Francesco!
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Victoria Park
        title: 71 Victoria Park Rd
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: fnicoli.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (44) 783-153-8798
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
#    copyright: Company Name
    enable: yes
#    quicklinks:
#      - alt: HTML5 UP
 #       text: 'Design: '
  #      url: https://www.html5up.net
    social:
 #     - icon: fa-twitter
  #      label: Twitter
   #     url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/nicoli.francesco.3/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/___fra00___/
      - icon: fa-github
        label: GitHub
        url: https://github.com/francesconicoli00
      - icon: fa-linkedin
        label: LinkedIn
        url: www.linkedin.com/in/francesco-nicolì
  image: ''
  name: Francesco Nicolì
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: sfgolden.jpg
        subtitle: A brief presentation
        title: About me
        url: blogs/biography1
      - image: Sailing_theme.jpg
        subtitle: My sailing experience
        title: Sailing
        url: blogs/sailing_1
      - image: piano_banner.jpg
        subtitle: My music experience
        title: Piano
        url: blogs/piano_1
      - image: pic04.jpg
        subtitle: All about me
        title: Aliquam
        url: blogs/aliquam
      - image: pic05.jpg
        subtitle: Risk Returm
        title: Analysis
        url: blogs/risk_return
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
      
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
