---
title: "Text Mining Analysis & Neural Network fit on Movie Data"
date: "2022-09-18"
description: Text Mining Analysis & Neural Network fit on Movie Data
draft: no
image: movie_banner.jpg
keywords: ''
slug: ml_final_project
categories:
- ''
- ''
---



<div id="part-1-text-mining-analysis" class="section level1">
<h1>Part 1: Text Mining Analysis</h1>
<div id="data-preprocessing" class="section level2">
<h2>Data Preprocessing</h2>
<p>Before taking on the Text Mining Analysis we intend to perform on the Movie
Data, we need to preprocess the <strong>tags dataset</strong>: the one containing the tags
from each user regarding each movie. The preprocessing consists of removing
duplicates, merging the tags in one line and removing special characters.</p>
<pre class="r"><code># Reading tags.csv file and keeping &quot;movieId&quot; and &quot;tags&quot; columns
tags &lt;- fread(&quot;C:/Users/optif/OneDrive/Desktop/academics/applied_statistics/Francesco_repository_1/data/tags-file2.csv&quot;)
tags &lt;- tags %&gt;%
  select(movieId, tag)

dim(tags) # print dimensions</code></pre>
<pre><code>## [1] 1093360       2</code></pre>
<pre class="r"><code># Removing duplicated movieTags and aggregating tags
tb &lt;- tags %&gt;%
  group_by(movieId) %&gt;%
  summarise(tag = paste(unlist(list(as.character(tag))), collapse = &quot; &quot;))

dim(tb) # print dimensions</code></pre>
<pre><code>## [1] 45251     2</code></pre>
<pre class="r"><code># Filter for tags with at least 100 words
tb &lt;- tb %&gt;%
  filter(as.numeric(sapply(strsplit(tag, &quot; &quot;), length)) &gt; 100)

dim(tb) # print dimensions</code></pre>
<pre><code>## [1] 2918    2</code></pre>
<pre class="r"><code># Removing special characters from tags
tb &lt;- tb %&gt;%
  mutate(tag = gsub(&quot;[[:punct:]]&quot;, &quot;&quot;, tag))

dim(tb) # print dimensions</code></pre>
<pre><code>## [1] 2918    2</code></pre>
<p>Our task is to build a <strong>Document Term Matrix</strong> containing individual movies as
documents and terms/words occurring in tags as columns. Furthermore, we decided
to create <strong>bi_grams</strong> in our dataset. Hence, we have to be careful as our
matrix will become sparse very quickly.</p>
<pre class="r"><code># Tags corpus
corp_tags &lt;- VCorpus(VectorSource(tb$tag))
inspect(corp_tags[1:5]) # inspecting first 5 rows of corpus</code></pre>
<pre><code>## &lt;&lt;VCorpus&gt;&gt;
## Metadata:  corpus specific: 0, document level (indexed): 0
## Content:  documents: 5
## 
## [[1]]
## &lt;&lt;PlainTextDocument&gt;&gt;
## Metadata:  7
## Content:  chars: 6244
## 
## [[2]]
## &lt;&lt;PlainTextDocument&gt;&gt;
## Metadata:  7
## Content:  chars: 2070
## 
## [[3]]
## &lt;&lt;PlainTextDocument&gt;&gt;
## Metadata:  7
## Content:  chars: 6945
## 
## [[4]]
## &lt;&lt;PlainTextDocument&gt;&gt;
## Metadata:  7
## Content:  chars: 894
## 
## [[5]]
## &lt;&lt;PlainTextDocument&gt;&gt;
## Metadata:  7
## Content:  chars: 1516</code></pre>
<pre class="r"><code># Creating the BigramTokenizer function for creating Bi-grams in the DTM
BigramTokenizer &lt;- function(x){
  NGramTokenizer(x, Weka_control(min=1, max=2))
}

corp_tags &lt;- tm_map(corp_tags, stripWhitespace)

# Converting corp_tags into DocumentTermMatrix object
DTM_tags_DF_IDF &lt;- DocumentTermMatrix(corp_tags, control = list(
            tolower = TRUE, # Converts to lowercase
            removeNumbers = TRUE, # Removes numbers
            stopwords = TRUE, # Removes common words with almost 0 info value
            removePunctuation = TRUE, # Even if we did it previously
            stripWhitespace = TRUE, # Removes white space characters
            tokenize = BigramTokenizer, # Setting Tokenizer parameter
            weighting = weightTfIdf)) # Setting weighting to Inverse Document
                                      # Frequency

dim(DTM_tags_DF_IDF) # print dimensions of DTM_tags_DF_IDF</code></pre>
<pre><code>## [1]   2918 338118</code></pre>
<pre class="r"><code>inspect(DTM_tags_DF_IDF[,c(1:5)]) # inspecting content of first 5</code></pre>
<pre><code>## &lt;&lt;DocumentTermMatrix (documents: 2918, terms: 5)&gt;&gt;
## Non-/sparse entries: 7/14583
## Sparsity           : 100%
## Maximal term length: 10
## Weighting          : term frequency - inverse document frequency (normalized) (tf-idf)
## Sample             :
##       Terms
## Docs    aardman   aaron  abduction  abortion  about
##   1      0.0000 0.00000     0.0000    0.0000 0.0000
##   1590   0.0241 0.00000     0.0000    0.0000 0.0000
##   1829   0.0000 0.00000     0.0111    0.0000 0.0000
##   2      0.0000 0.00000     0.0000    0.0000 0.0000
##   2175   0.0000 0.00328     0.0000    0.0000 0.0000
##   2178   0.0000 0.00000     0.0000    0.0000 0.0244
##   2210   0.0000 0.04102     0.0000    0.0000 0.0000
##   3      0.0000 0.00000     0.0000    0.0000 0.0000
##   600    0.0000 0.00877     0.0000    0.0000 0.0000
##   810    0.0000 0.00000     0.0000    0.0234 0.0000</code></pre>
<pre class="r"><code>                                            # columns of DTM_tags_DF_IDF</code></pre>
<p>In this first step of the Text Mining phase, we decided to create a
Document-Term Matrix by converting all characters to <em>lowercase</em> characters,
removing all <em>numbers</em>, removing <em>common words</em> (since those words don’t provide
informational value), removing <em>punctuation</em> and stripping additional white spaces
in the strings. We also decided to add <strong>bi-grams</strong> to the DTM in order to
include an ad-hoc analysis of the many two-word tags coming in the dataset.</p>
<p>In addition, we created the DTM object that stores the number of occurrences
computed using the <strong>Term Frequency - Inverse Document Frequency</strong> adjustment
rule. This method allows us to take into account both the frequency of terms in
a tag and the frequency of tags containing that term, thus identifying documents
with frequent occurrences of rare terms.</p>
<p>In the next step, we address sparsity for both single words and bi-grams.</p>
<pre class="r"><code># Removing sparse tokens from the DTM_tags_DF_IDF
DTM_tags_TF_IDF2 &lt;- removeSparseTerms(DTM_tags_DF_IDF, 0.996) # 99.6% maximum
                                                              # sparsity

# Checking for dimensions of new DTM
dim(DTM_tags_TF_IDF2)</code></pre>
<pre><code>## [1] 2918 6060</code></pre>
<pre class="r"><code># Printing the first five terms of the new DTM
inspect(DTM_tags_TF_IDF2[,c(1:5)])</code></pre>
<pre><code>## &lt;&lt;DocumentTermMatrix (documents: 2918, terms: 5)&gt;&gt;
## Non-/sparse entries: 175/14415
## Sparsity           : 99%
## Maximal term length: 10
## Weighting          : term frequency - inverse document frequency (normalized) (tf-idf)
## Sample             :
##       Terms
## Docs    academy  action  adventure    afi  animation
##   1722   0.0000  0.0686          0 0.0000          0
##   2542   0.0343  0.0000          0 0.0000          0
##   2566   0.0406  0.0000          0 0.0000          0
##   2583   0.1306  0.0000          0 0.0000          0
##   2596   0.0358  0.0000          0 0.0000          0
##   2604   0.1038  0.0000          0 0.0000          0
##   335    0.0000  0.0000          0 0.0390          0
##   467    0.0000  0.0439          0 0.0000          0
##   868    0.0000  0.0000          0 0.0359          0
##   900    0.0000  0.0000          0 0.0358          0</code></pre>
<pre class="r"><code># Return the number of bi-grams in the DTM_tags_TF_IDF2
sum(as.numeric(sapply(strsplit(trimws(DTM_tags_TF_IDF2$dimnames$Terms), &quot; &quot;),
                      length)) &gt; 1)</code></pre>
<pre><code>## [1] 2839</code></pre>
<p>In this last step of the Text Mining section, we filtered for terms with a
<em>sparsity</em> less or equal to <strong>99.6%</strong>. This value seems reasonable since 0.4%
of the tags is around 12 tags: we definitely do not want to include tokens
appearing in less than 12 tags but tokens that appear in more than 12 tags can
turn out to be useful for the analysis. In conclusion, we compute the number of
bi-grams present in our Document Term Matrix: <strong>2839</strong> bi-grams out of 6060 words
filtered.</p>
</div>
</div>
<div id="principle-component-analysis" class="section level1">
<h1>Principle Component Analysis</h1>
<p>Now that we have a DTM, we can use it in an <strong>unsupervised machine learning</strong>
<strong>algorithm</strong> that can reduce the dimensionality of the data.
Specifically we have terms/words that describe each movie, however likely
we have way too many columns and should only use a <strong>reduced amount of columns</strong>
in our further analysis. For example we may wish to run a classification
algorithm such as an SVM as a final step in order to be able to create a model
that can predict a movie’s rating based on some features, including the features
produced as a result of running the PCA.</p>
<p>Therefore our next task is to run the <strong>PCA</strong> on the Document Term Matrix that
we designed above. As a result of the PCA we should provide the PC
coordinates/scores to be used as features in Part 3. Crucially, we must decide
on the number of these new columns (containing the PC scores) that should be
used.</p>
<pre class="r"><code># Converting the DTM object into a tibble first
m &lt;- as.matrix(DTM_tags_TF_IDF2)
DTM_tags_tbl &lt;- as_tibble(m)

# Standardizing the dataset
DTM_pca &lt;- scale(DTM_tags_tbl, center = TRUE, scale = TRUE)

# Running PCA on DTM_pca
tags_pca &lt;- prcomp(DTM_pca, center = FALSE, scale. = FALSE)</code></pre>
<p>After <em>standardizing</em> the dataset and running the <em>PCA</em> on it, we are ready to
perform the <strong>Analysis of the Variance</strong>.</p>
<pre class="r"><code># &quot;Variance Explained&quot; as vector of the SDev^2 explained by each PC
VE &lt;- tags_pca$sdev^2

# &quot;Percentage of Variance Explained&quot; as proportion of total variance explained
# by each PC
PVE &lt;- VE/sum(VE)*100

# Cumulative Percentage of Variance Explained
CPVE &lt;- cumsum(PVE)

# Creating Data frame object containing data about Variance Explained by each PC
df &lt;- data.frame(PC = c(1:length(tags_pca$sdev)), 
                 var_explained = VE,
                 cum_sum_PVE = CPVE)

# Building Scree Plot of the Variance Explained
df %&gt;%
  ggplot(aes(x = PC, y = var_explained)) +
  geom_point(size = 4) +
  geom_line() + 
  scale_x_continuous(breaks = seq(0,3000,250)) +
  geom_hline(yintercept = 1, linetype = &quot;dashed&quot;, color = &quot;red&quot;, size = 1.2) +
  labs(x = &quot;PC Number&quot;, y = &quot;VE&quot;, 
       title = &quot;Scree Plot&quot;, 
       subtitle = &quot;PCA on tags Data&quot;) +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15, face = &quot;bold&quot;, color = &quot;blue&quot;),
        plot.title = element_text(size = 18, color = &quot;blue&quot;),
        plot.subtitle = element_text(size = 15, color = &quot;blue&quot;)
  )</code></pre>
<p><img src="/blogs/brexit_project_files/figure-html/Analysis%20of%20Variance-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Since it is difficult to pinpoint where the elbow occurs exactly, we are going
to build another Scree Plot showing the Variance Explained by all the PCs from
the 1st to the 50th.</p>
<pre class="r"><code># Building Scree Plot of the Variance Explained for the first 50 PCs
df[c(1:50),] %&gt;%
  ggplot(aes(x = PC, y = var_explained)) +
  geom_point(size = 4) +
  geom_line() + 
  scale_x_continuous(breaks = seq(0,50,5)) +
  geom_hline(yintercept = 1, linetype = &quot;dashed&quot;, color = &quot;red&quot;, size = 1.2) +
  labs(x = &quot;PC Number&quot;, y = &quot;VE&quot;, 
       title = &quot;Scree Plot&quot;, 
       subtitle = &quot;PCA on Tags Data&quot;) +
  theme(axis.text = element_text(size = 15),
        axis.title = element_text(size = 15, face = &quot;bold&quot;, color = &quot;blue&quot;),
        plot.title = element_text(size = 18, color = &quot;blue&quot;),
        plot.subtitle = element_text(size = 15, color = &quot;blue&quot;)
  )</code></pre>
<p><img src="/blogs/brexit_project_files/figure-html/Analysis%20of%20Variance%20Visualisation-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>As we can see by the Scree Plot, the elbow occurs at the 10th PC. In fact, after
this PC, the amount of variance explained tends to flatten out. Hence, we are
going to keep <strong>10 PCs</strong> for our further analysis.</p>
<pre class="r"><code># Dataset containing the number of PCs we decided to keep (10)
final_dataset &lt;- tags_pca$x[,c(1:10)]
dim(final_dataset) # Print dimensions</code></pre>
<pre><code>## [1] 2918   10</code></pre>
<pre class="r"><code># Adding movieId column back to the dataset
features_pca &lt;- data.frame(tb$movieId, final_dataset) # Adding movieId column</code></pre>
</div>
<div id="part-2-svm-and-neural-network-fit" class="section level1">
<h1>Part 2: SVM and Neural Network fit</h1>
<div id="data-preprocessing-1" class="section level2">
<h2>Data Preprocessing</h2>
<p>Before fitting the ML algos we intend to (Support Vector Machine &amp; Artificial
Neural Network), we need to <strong>preprocess</strong> our data to get the final dataset we
are going to use in our analysis. We want to use the <strong>Principal Components</strong> we
kept from Part 1 as the first <strong>10 variables</strong>. In addition, we want to create
<strong>20 dummy variables</strong>: those variables are gonna be binary variables and their
value is gonna depend on whether the movie belongs to a certain <strong>genre</strong> or not.
Finally, we are gonna add the <strong>average rating</strong> for each movie (the 31st
variable in our dataset), which is our <strong>output variable</strong> (the one we are gonna
try to predict).</p>
<p>Hence, we are going to import the dataset containing the average rating for each
movie (<em>ratings</em>) and the dataset containing the name and genre of each movie
(<em>movies</em>). Afterwards, we are going to <strong>join</strong> the latter two datasets with the
one containing the Principal Components.</p>
<pre class="r"><code># Loading ratings dataset
ratings &lt;- fread(&quot;C:/Users/optif/OneDrive/Desktop/academics/applied_statistics/Francesco_repository_1/data/ratings_actual.csv&quot;)

# Loading movies dataset
movies &lt;- fread(&quot;C:/Users/optif/OneDrive/Desktop/academics/applied_statistics/Francesco_repository_1/data/movies_actual.csv&quot;)

# Joining ratings and movies data
movies_ratings &lt;- left_join(ratings, movies, by = c(&quot;movieId&quot;=&quot;movieId&quot;))

# Joining movies_ratings and features_pca dataset
final_dataset &lt;- left_join(features_pca, movies_ratings,
                           by = c(&quot;tb.movieId&quot;=&quot;movieId&quot;))

# Creating vector with all genres in dataset
genres_vec &lt;- unique(unlist(strsplit(movies$genres, split = &quot;\\|&quot;)))

# Adding dummy variables to final_dataset for each genre
for(i in genres_vec){
  final_dataset &lt;- data.frame(final_dataset,
                              as.numeric(str_detect(final_dataset$genres, i)))
}

# Fixing column names in the final_dataset
colnames(final_dataset)[15:34] &lt;- genres_vec

# Dropping columns we do not need
final_dataset &lt;- final_dataset %&gt;%
  select(-genres, -title, -tb.movieId)</code></pre>
</div>
</div>
<div id="first-task-support-vector-machine" class="section level1">
<h1>First Task: Support Vector Machine</h1>
<pre class="r"><code># Converting the column with average rating into a binary column
final_dataset_svm &lt;- final_dataset %&gt;%
  mutate(avg_rating = ifelse(avg_rating&gt;=3.75, 1, 0))

# Split the data into training and testing set
set.seed(1234)
train_test &lt;- initial_split(final_dataset_svm, prop = 0.8)
data_svm_train &lt;- training(train_test)
data_svm_test &lt;- testing(train_test)</code></pre>
<p>Now we can try different types of SVM: Linear, Radial and Poly.</p>
<pre class="r"><code># Creating grid containing hyper parameters to tune
grid &lt;- expand.grid(sigma = c(0.016, 0.017, 0.018, 0.019, 0.020),
                    C = c(1,2,3,4,5,6,7,8,9,10))

# Training Radial SVM
SVM_Radial &lt;- caret::train(
  as.factor(avg_rating) ~ .,
  data = data_svm_train,
  method = &quot;svmRadial&quot;, # Radial kernel      
  preProcess = c(&quot;center&quot;, &quot;scale&quot;),  # center &amp; scale the data
  trControl = trainControl(method = &quot;cv&quot;, number = 10), #cross-validation (10-fold) 
  tuneGrid = grid # grid created above
)

# Printing details about the Radial SVM tuned
print(SVM_Radial)</code></pre>
<pre><code>## Support Vector Machines with Radial Basis Function Kernel 
## 
## 2334 samples
##   30 predictor
##    2 classes: &#39;0&#39;, &#39;1&#39; 
## 
## Pre-processing: centered (30), scaled (30) 
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 2101, 2101, 2100, 2101, 2101, 2100, ... 
## Resampling results across tuning parameters:
## 
##   sigma  C   Accuracy  Kappa
##   0.016   1  0.787     0.446
##   0.016   2  0.790     0.462
##   0.016   3  0.793     0.479
##   0.016   4  0.797     0.491
##   0.016   5  0.794     0.486
##   0.016   6  0.795     0.491
##   0.016   7  0.794     0.488
##   0.016   8  0.792     0.484
##   0.016   9  0.790     0.482
##   0.016  10  0.790     0.482
##   0.017   1  0.785     0.442
##   0.017   2  0.791     0.466
##   0.017   3  0.793     0.477
##   0.017   4  0.795     0.486
##   0.017   5  0.795     0.490
##   0.017   6  0.794     0.488
##   0.017   7  0.793     0.487
##   0.017   8  0.792     0.486
##   0.017   9  0.789     0.479
##   0.017  10  0.789     0.480
##   0.018   1  0.786     0.445
##   0.018   2  0.790     0.463
##   0.018   3  0.796     0.487
##   0.018   4  0.794     0.485
##   0.018   5  0.794     0.488
##   0.018   6  0.793     0.487
##   0.018   7  0.794     0.489
##   0.018   8  0.790     0.482
##   0.018   9  0.791     0.484
##   0.018  10  0.789     0.480
##   0.019   1  0.787     0.448
##   0.019   2  0.790     0.465
##   0.019   3  0.795     0.485
##   0.019   4  0.795     0.489
##   0.019   5  0.792     0.484
##   0.019   6  0.793     0.487
##   0.019   7  0.790     0.482
##   0.019   8  0.791     0.484
##   0.019   9  0.790     0.483
##   0.019  10  0.789     0.482
##   0.020   1  0.788     0.452
##   0.020   2  0.790     0.467
##   0.020   3  0.795     0.484
##   0.020   4  0.794     0.488
##   0.020   5  0.793     0.484
##   0.020   6  0.794     0.489
##   0.020   7  0.790     0.481
##   0.020   8  0.792     0.488
##   0.020   9  0.790     0.483
##   0.020  10  0.792     0.489
## 
## Accuracy was used to select the optimal model using the largest value.
## The final values used for the model were sigma = 0.016 and C = 4.</code></pre>
<pre class="r"><code># Display training accuracy metrics
confusionMatrix(SVM_Radial)</code></pre>
<pre><code>## Cross-Validated (10 fold) Confusion Matrix 
## 
## (entries are percentual average cell counts across resamples)
##  
##           Reference
## Prediction    0    1
##          0 62.8 14.4
##          1  5.8 17.0
##                             
##  Accuracy (average) : 0.7973</code></pre>
<pre class="r"><code># Model validation on the test set
Radial_test_validation &lt;- predict(SVM_Radial, data_svm_test)
confusionMatrix(data = Radial_test_validation, as.factor(data_svm_test$avg_rating))</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 380  78
##          1  29  97
##                                         
##                Accuracy : 0.817         
##                  95% CI : (0.783, 0.847)
##     No Information Rate : 0.7           
##     P-Value [Acc &gt; NIR] : 8.82e-11      
##                                         
##                   Kappa : 0.525         
##                                         
##  Mcnemar&#39;s Test P-Value : 3.48e-06      
##                                         
##             Sensitivity : 0.929         
##             Specificity : 0.554         
##          Pos Pred Value : 0.830         
##          Neg Pred Value : 0.770         
##              Prevalence : 0.700         
##          Detection Rate : 0.651         
##    Detection Prevalence : 0.784         
##       Balanced Accuracy : 0.742         
##                                         
##        &#39;Positive&#39; Class : 0             
## </code></pre>
<p>In the output of the SVM_Radial model, we can see that the highest accuracy is
achieved by setting the <strong>Cost</strong> hyper parameter at <strong>5</strong> and the <strong>Sigma</strong> hyper
parameter at <strong>0.016</strong>. The <em>out-of-sample</em> accuracy obtained with the SVM Radial
model and the stated hyper parameters is <strong>82.02%</strong>. We can now try to see if
Linear and Poly SVM can perform better than Radial SVM.</p>
<pre class="r"><code># Training Poly SVM
SVM_Poly &lt;- caret::train(
  as.factor(avg_rating) ~ .,
  data = data_svm_train,
  method = &quot;svmPoly&quot;,
  trControl = trainControl(method = &quot;cv&quot;, number = 10),
  preProcess = c(&quot;center&quot;,&quot;scale&quot;),
  tuneLength = 4) # Parameter set to tune the 4 default values for the 3
                  # hyper parameters: degree, scale and C

# Print SVM_Poly details
print(SVM_Poly)</code></pre>
<pre><code>## Support Vector Machines with Polynomial Kernel 
## 
## 2334 samples
##   30 predictor
##    2 classes: &#39;0&#39;, &#39;1&#39; 
## 
## Pre-processing: centered (30), scaled (30) 
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 2101, 2100, 2100, 2101, 2100, 2101, ... 
## Resampling results across tuning parameters:
## 
##   degree  scale  C     Accuracy  Kappa  
##   1       0.001  0.25  0.687     0.00562
##   1       0.001  0.50  0.704     0.08209
##   1       0.001  1.00  0.725     0.17620
##   1       0.001  2.00  0.746     0.26759
##   1       0.010  0.25  0.752     0.29198
##   1       0.010  0.50  0.770     0.37086
##   1       0.010  1.00  0.779     0.40816
##   1       0.010  2.00  0.781     0.42290
##   1       0.100  0.25  0.781     0.42608
##   1       0.100  0.50  0.785     0.44063
##   1       0.100  1.00  0.782     0.43540
##   1       0.100  2.00  0.783     0.44076
##   1       1.000  0.25  0.783     0.44126
##   1       1.000  0.50  0.784     0.44468
##   1       1.000  1.00  0.784     0.44602
##   1       1.000  2.00  0.785     0.44866
##   2       0.001  0.25  0.705     0.08382
##   2       0.001  0.50  0.725     0.17620
##   2       0.001  1.00  0.746     0.26759
##   2       0.001  2.00  0.763     0.34251
##   2       0.010  0.25  0.773     0.38134
##   2       0.010  0.50  0.780     0.41482
##   2       0.010  1.00  0.784     0.43382
##   2       0.010  2.00  0.788     0.45409
##   2       0.100  0.25  0.791     0.47526
##   2       0.100  0.50  0.787     0.47325
##   2       0.100  1.00  0.786     0.47244
##   2       0.100  2.00  0.781     0.46304
##   2       1.000  0.25  0.766     0.43867
##   2       1.000  0.50  0.764     0.43946
##   2       1.000  1.00  0.764     0.44065
##   2       1.000  2.00  0.766     0.44599
##   3       0.001  0.25  0.715     0.13218
##   3       0.001  0.50  0.738     0.23027
##   3       0.001  1.00  0.757     0.31701
##   3       0.001  2.00  0.775     0.39035
##   3       0.010  0.25  0.785     0.42563
##   3       0.010  0.50  0.785     0.43666
##   3       0.010  1.00  0.790     0.45955
##   3       0.010  2.00  0.789     0.46114
##   3       0.100  0.25  0.776     0.45006
##   3       0.100  0.50  0.772     0.45008
##   3       0.100  1.00  0.761     0.43327
##   3       0.100  2.00  0.763     0.44245
##   3       1.000  0.25  0.724     0.37033
##   3       1.000  0.50  0.713     0.34551
##   3       1.000  1.00  0.714     0.35113
##   3       1.000  2.00  0.704     0.32593
## 
## Accuracy was used to select the optimal model using the largest value.
## The final values used for the model were degree = 2, scale = 0.1 and C = 0.25.</code></pre>
<pre class="r"><code># Display training accuracy metrics
confusionMatrix(SVM_Poly)</code></pre>
<pre><code>## Cross-Validated (10 fold) Confusion Matrix 
## 
## (entries are percentual average cell counts across resamples)
##  
##           Reference
## Prediction    0    1
##          0 62.4 14.7
##          1  6.2 16.7
##                             
##  Accuracy (average) : 0.7909</code></pre>
<pre class="r"><code># Model validation on the test set
Poly_test_validation &lt;- predict(SVM_Poly, data_svm_test)
confusionMatrix(data = Poly_test_validation, as.factor(data_svm_test$avg_rating))</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 380  81
##          1  29  94
##                                         
##                Accuracy : 0.812         
##                  95% CI : (0.778, 0.843)
##     No Information Rate : 0.7           
##     P-Value [Acc &gt; NIR] : 5.97e-10      
##                                         
##                   Kappa : 0.51          
##                                         
##  Mcnemar&#39;s Test P-Value : 1.16e-06      
##                                         
##             Sensitivity : 0.929         
##             Specificity : 0.537         
##          Pos Pred Value : 0.824         
##          Neg Pred Value : 0.764         
##              Prevalence : 0.700         
##          Detection Rate : 0.651         
##    Detection Prevalence : 0.789         
##       Balanced Accuracy : 0.733         
##                                         
##        &#39;Positive&#39; Class : 0             
## </code></pre>
<p>The <strong>Poly SVM</strong> performs slightly better than the <strong>Radial SVM</strong> out of sample,
since the out-of-sample accuracy is <strong>82.19%</strong>. The hyper parameters selected
based on the 10-fold cross validation are the following: <strong>degree</strong> of <strong>2</strong>,
<strong>scale</strong> of <strong>0.1</strong> and <strong>Cost</strong> of <strong>0.5</strong>. Now we can verify if the accuracy
improves by using a <strong>Linear SVM</strong>. In this case, though, we cannot use the
train function from the caret package since it is too computationally expensive
to train a Linear SVM with caret (we measured the time it takes). Hence we are
going to use the svm function from the e1071 package.</p>
<pre class="r"><code># We are going to tune the only hyper parameter we have in the Linear SVM
# semi-automatically: by building a for loop testing for the values we want
# We first create a vector where to add the values of the Accuracy obtained
# at each step
Accuracy &lt;- c()

# Here we build the for-loop
for(i in 1:10){
  SMV_Linear &lt;- svm(as.factor(avg_rating) ~ .,
                    data = data_svm_train,
                    kernel = &quot;linear&quot;,
                    cost = i,
                    scale = TRUE) # We choose to standardize the data

  # Test performance on out-of-sample data
  Linear_test_validation &lt;- predict(SMV_Linear, data_svm_test)
  Lin_matrix &lt;- confusionMatrix(data = Linear_test_validation,
                                as.factor(data_svm_test$avg_rating))
  
  # Add the Accuracy obtained to the Accuracy list
  Accuracy &lt;- c(Accuracy, Lin_matrix$overall[1])
  
}

# Printing the values of Accuracy together with Cost values
Accuracy_dataset &lt;- data.frame(seq(1,10,1), Accuracy)
Accuracy_dataset</code></pre>
<pre><code>##    seq.1..10..1. Accuracy
## 1              1    0.803
## 2              2    0.805
## 3              3    0.805
## 4              4    0.805
## 5              5    0.805
## 6              6    0.805
## 7              7    0.805
## 8              8    0.805
## 9              9    0.805
## 10            10    0.805</code></pre>
<p>As we can see by the dataset reporting the accuracy of the Linear SVM for the
different values of the <strong>cost</strong>, the best accuracy is achieved with a Cost higher
or equal to <strong>2</strong>: the model performs better for a <strong>higher penalization</strong> of the
<em>margin violations</em>. It is possible to see that the accuracy is the same for any
value of the cost that is at least equal to 2: <strong>80.48%</strong>. It is important to
highlight that the accuracy measured is <strong>out-of-sample</strong>. Based on the data, the
Linear SVM is the worst performing among all the SVM models built.</p>
<p>As we could see in all the three models built, though, <em>over fitting</em> is not an
issue: besides measuring accuracy in-sample, we also measured accuracy
out-of-sample and this actually turned out to be higher than the in-sample one.
In addition, the hyper parameters were selected using the 10-fold cross
validation procedure. Hence, the selection was performed taking into account the
<strong>out-of-sample performance</strong> reported at each iteration.</p>
<p>Now, we will compare the results obtained with another classifier algorithm, to
test the <strong>relative effectiveness</strong> of our SVM. The algorithm we are going to
use to compare our results is the <strong>logistic regression</strong>.</p>
<pre class="r"><code># Training the Logistic model
logistic &lt;- glm(avg_rating ~ .,
                family=&quot;binomial&quot;,
                data_svm_train)

# Printing summary of logistic
summary(logistic)</code></pre>
<pre><code>## 
## Call:
## glm(formula = avg_rating ~ ., family = &quot;binomial&quot;, data = data_svm_train)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -3.143  -0.679  -0.406   0.547   2.896  
## 
## Coefficients:
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)           -0.5732     0.1789   -3.20  0.00135 ** 
## PC1                    0.2336     0.0207   11.30  &lt; 2e-16 ***
## PC2                    0.0308     0.0192    1.60  0.10918    
## PC3                   -0.1045     0.0464   -2.25  0.02441 *  
## PC4                    0.0843     0.0232    3.63  0.00028 ***
## PC5                    0.0751     0.0219    3.43  0.00061 ***
## PC6                   -0.1232     0.0182   -6.78  1.2e-11 ***
## PC7                    0.1530     0.0222    6.90  5.1e-12 ***
## PC8                    0.0060     0.0181    0.33  0.74006    
## PC9                   -0.0306     0.0230   -1.33  0.18280    
## PC10                  -0.1246     0.0219   -5.68  1.3e-08 ***
## Adventure              0.0515     0.1884    0.27  0.78437    
## Animation              1.2090     0.3137    3.85  0.00012 ***
## Children              -0.8835     0.3811   -2.32  0.02045 *  
## Comedy                -0.3714     0.1698   -2.19  0.02868 *  
## Fantasy               -1.0010     0.2379   -4.21  2.6e-05 ***
## Romance               -0.2382     0.1619   -1.47  0.14113    
## Drama                  0.1658     0.1515    1.09  0.27372    
## Action                 0.2812     0.1807    1.56  0.11967    
## Crime                  0.3683     0.1659    2.22  0.02644 *  
## Thriller              -0.4781     0.1574   -3.04  0.00239 ** 
## Horror                -1.9600     0.2804   -6.99  2.8e-12 ***
## Mystery                0.1253     0.2061    0.61  0.54322    
## `Sci-Fi`              -0.6179     0.2646   -2.33  0.01955 *  
## IMAX                   0.0454     0.3416    0.13  0.89415    
## Documentary            0.8720     0.3836    2.27  0.02302 *  
## War                    0.0217     0.2732    0.08  0.93665    
## Musical               -0.9551     0.3882   -2.46  0.01388 *  
## Western               -0.5525     0.4398   -1.26  0.20909    
## `Film-Noir`            0.4023     0.6386    0.63  0.52872    
## `(no genres listed)`  -0.6393     1.1429   -0.56  0.57588    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 2904.9  on 2333  degrees of freedom
## Residual deviance: 2053.4  on 2303  degrees of freedom
## AIC: 2115
## 
## Number of Fisher Scoring iterations: 6</code></pre>
<pre class="r"><code># We get the probability of being an excellent movie
prob_excellent&lt;-predict(logistic, data_svm_test, type=&quot;response&quot;)

# Create the binary vector based on threshold 0.5
one_or_zero&lt;-ifelse(prob_excellent&gt;0.5,&quot;1&quot;,&quot;0&quot;)

# Creating a vector of predictions
p_class&lt;-factor(one_or_zero,levels=levels(as.factor(data_svm_test$avg_rating)))

# Computing and printing Confusion Matrix
con2&lt;-confusionMatrix(p_class, as.factor(data_svm_test$avg_rating), positive=&quot;1&quot;)

# Printing Accuracy measure
con2$overall[1]</code></pre>
<pre><code>## Accuracy 
##    0.807</code></pre>
<p>As we can see by the <strong>accuracy</strong> calculated <strong>out-of-sample</strong> (<strong>80.65%</strong>), the
logistic regression model performs <em>slightly worse</em> than the <strong>Radial</strong> and
<strong>Poly SVM</strong> but <em>slightly better</em> than the <strong>Linear SVM</strong>.</p>
<p>At the end of the exploration of all the models, we present our best performing
model: the Poly SVM, with a <strong>degree</strong> parameter of <strong>2</strong>, a <strong>scale</strong> parameter
of <strong>0.1</strong> and a <strong>cost</strong> parameter of <strong>0.5</strong>.</p>
<p>As the last step of the first task, we are going to re-tune our best SVM model
on the initial dataset changing the <strong>threshold</strong> for a rating to be considered
an excellent rating (from <strong>3.75</strong> to <strong>4</strong>), in order to see how the performance
changes.</p>
<pre class="r"><code># Getting data with threshold at 4
final_dataset_svm2 &lt;- final_dataset %&gt;%
  mutate(avg_rating = ifelse(avg_rating&gt;=4, 1, 0))

# Split the data into training and testing set
set.seed(3456)
train_test2 &lt;- initial_split(final_dataset_svm2, prop = 0.8)
data_svm_train2 &lt;- training(train_test2)
data_svm_test2 &lt;- testing(train_test2)

# Training Poly SVM
SVM_Poly2 &lt;- caret::train(
  as.factor(avg_rating) ~ .,
  data = data_svm_train2,
  method = &quot;svmPoly&quot;,
  trControl = trainControl(method = &quot;cv&quot;, number = 10),
  preProcess = c(&quot;center&quot;,&quot;scale&quot;),
  tuneLength = 4) # Parameter set to tune the 4 default values for the 3
                  # hyper parameters: degree, scale and C

# Print SVM_Poly details
print(SVM_Poly2)</code></pre>
<pre><code>## Support Vector Machines with Polynomial Kernel 
## 
## 2334 samples
##   30 predictor
##    2 classes: &#39;0&#39;, &#39;1&#39; 
## 
## Pre-processing: centered (30), scaled (30) 
## Resampling: Cross-Validated (10 fold) 
## Summary of sample sizes: 2101, 2102, 2100, 2101, 2100, 2101, ... 
## Resampling results across tuning parameters:
## 
##   degree  scale  C     Accuracy  Kappa 
##   1       0.001  0.25  0.920     0.0000
##   1       0.001  0.50  0.920     0.0000
##   1       0.001  1.00  0.920     0.0000
##   1       0.001  2.00  0.920     0.0000
##   1       0.010  0.25  0.920     0.0000
##   1       0.010  0.50  0.920     0.0000
##   1       0.010  1.00  0.920     0.0000
##   1       0.010  2.00  0.920     0.0000
##   1       0.100  0.25  0.920     0.0000
##   1       0.100  0.50  0.920     0.0000
##   1       0.100  1.00  0.920     0.0000
##   1       0.100  2.00  0.920     0.0000
##   1       1.000  0.25  0.920     0.0000
##   1       1.000  0.50  0.920     0.0000
##   1       1.000  1.00  0.920     0.0000
##   1       1.000  2.00  0.920     0.0000
##   2       0.001  0.25  0.920     0.0000
##   2       0.001  0.50  0.920     0.0000
##   2       0.001  1.00  0.920     0.0000
##   2       0.001  2.00  0.920     0.0000
##   2       0.010  0.25  0.920     0.0000
##   2       0.010  0.50  0.921     0.0184
##   2       0.010  1.00  0.923     0.0671
##   2       0.010  2.00  0.925     0.1204
##   2       0.100  0.25  0.922     0.2046
##   2       0.100  0.50  0.922     0.2536
##   2       0.100  1.00  0.919     0.2626
##   2       0.100  2.00  0.913     0.2696
##   2       1.000  0.25  0.900     0.2489
##   2       1.000  0.50  0.892     0.2246
##   2       1.000  1.00  0.885     0.1912
##   2       1.000  2.00  0.886     0.2098
##   3       0.001  0.25  0.920     0.0000
##   3       0.001  0.50  0.920     0.0000
##   3       0.001  1.00  0.920     0.0000
##   3       0.001  2.00  0.920     0.0000
##   3       0.010  0.25  0.923     0.0671
##   3       0.010  0.50  0.922     0.0657
##   3       0.010  1.00  0.925     0.1457
##   3       0.010  2.00  0.925     0.1695
##   3       0.100  0.25  0.912     0.2460
##   3       0.100  0.50  0.915     0.3072
##   3       0.100  1.00  0.908     0.2956
##   3       0.100  2.00  0.903     0.2873
##   3       1.000  0.25  0.865     0.2241
##   3       1.000  0.50  0.862     0.2201
##   3       1.000  1.00  0.853     0.2081
##   3       1.000  2.00  0.853     0.2089
## 
## Accuracy was used to select the optimal model using the largest value.
## The final values used for the model were degree = 3, scale = 0.01 and C = 1.</code></pre>
<pre class="r"><code># Display training accuracy metrics
confusionMatrix(SVM_Poly2)</code></pre>
<pre><code>## Cross-Validated (10 fold) Confusion Matrix 
## 
## (entries are percentual average cell counts across resamples)
##  
##           Reference
## Prediction    0    1
##          0 91.8  7.2
##          1  0.2  0.7
##                             
##  Accuracy (average) : 0.9254</code></pre>
<pre class="r"><code># Model validation on the test set
Poly_test_validation2 &lt;- predict(SVM_Poly2, data_svm_test2)
confusionMatrix(data = Poly_test_validation2, as.factor(data_svm_test2$avg_rating))</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   0   1
##          0 529  43
##          1   1  11
##                                       
##                Accuracy : 0.925       
##                  95% CI : (0.9, 0.945)
##     No Information Rate : 0.908       
##     P-Value [Acc &gt; NIR] : 0.0845      
##                                       
##                   Kappa : 0.31        
##                                       
##  Mcnemar&#39;s Test P-Value : 6.37e-10    
##                                       
##             Sensitivity : 0.998       
##             Specificity : 0.204       
##          Pos Pred Value : 0.925       
##          Neg Pred Value : 0.917       
##              Prevalence : 0.908       
##          Detection Rate : 0.906       
##    Detection Prevalence : 0.979       
##       Balanced Accuracy : 0.601       
##                                       
##        &#39;Positive&#39; Class : 0           
## </code></pre>
<p>After tuning the <strong>Poly SVM</strong> on the dataset again with a <strong>different label</strong>
(the new threshold for excellent rated movie set at 4), we can see that the
out-of-sample accuracy of the model is <strong>higher</strong> than the one obtained in the
previous case (threshold for excellent movie at 3.75): it is <strong>92.5%</strong> compared
to the <strong>82.2%</strong> obtained previously. In addition, the optimal hyper parameters
are different in this case: the <strong>degree</strong> is now <strong>3</strong>, the <strong>scale</strong> is <strong>0.01</strong>
and the <strong>Cost</strong> is <strong>1</strong>. In this model, a <strong>higher penalization</strong> for data points
over the boundary and a <strong>higher grade</strong> lead to a <strong>higher accuracy</strong>.</p>
<p>We could explain this result by thinking to the fact that a higher threshold
changes the distribution of “excellent” and “non-excellent” movies in the
D-dimensional space (D being 30 in this case), while all the predictive
variables stay the same. Most likely, this change in the “distribution” led to
less “overlap” between the two types of observations (excellent and
non-excellent), thus making it easier for the SVM to <em>linearly separate</em> the Data
in the infinite-dimensional space. This hypothesis is actually supported by a
higher <strong>Cost</strong> parameter compared to the one obtained previously: the model
allows for less <em>“violation”</em> of the margin, thus increasing
the accuracy of the model.</p>
</div>
<div id="second-task-artificial-neural-network" class="section level1">
<h1>Second Task: Artificial Neural Network</h1>
<pre class="r"><code># We first split the data
set.seed(2222)
train_test_split_ann &lt;- initial_split(final_dataset, prop = 0.8)
train_tbl_ann &lt;- training(train_test_split_ann)
test_tbl_ann  &lt;- testing(train_test_split_ann)
cat(&quot;Dimensions of the training set is: &quot;, dim(train_tbl_ann), &quot;\n&quot;)</code></pre>
<pre><code>## Dimensions of the training set is:  2334 31</code></pre>
<pre class="r"><code># Create the recipe object
recipe_obj &lt;- recipe(avg_rating ~ ., data = train_tbl_ann) %&gt;%
  step_center(all_numeric_predictors(), -all_outcomes()) %&gt;%
  step_scale(all_numeric_predictors(), -all_outcomes()) %&gt;%
  prep(data = train_tbl_ann)

# Creating X and Y sets
x_train_ann &lt;- bake(recipe_obj, new_data = train_tbl_ann) %&gt;% select(-avg_rating)
x_test_ann  &lt;- bake(recipe_obj, new_data = test_tbl_ann) %&gt;% select(-avg_rating)
glimpse(x_train_ann)</code></pre>
<pre><code>## Rows: 2,334
## Columns: 30
## $ PC1                  &lt;dbl&gt; 0.3240, 0.1489, -0.0483, -0.1228, -1.3840, 0.9437…
## $ PC2                  &lt;dbl&gt; -0.857, -0.489, -0.632, -0.849, -0.250, 3.021, -0…
## $ PC3                  &lt;dbl&gt; -0.2205, 0.3133, -0.1200, -0.0688, -0.3191, -0.71…
## $ PC4                  &lt;dbl&gt; 0.6341, 0.4375, -0.2251, 0.7456, 1.3945, -5.2388,…
## $ PC5                  &lt;dbl&gt; -0.08849, 0.28787, -0.32372, -0.08774, 3.35991, 0…
## $ PC6                  &lt;dbl&gt; 0.274605, -0.473682, 0.000267, -0.264130, -0.1393…
## $ PC7                  &lt;dbl&gt; 0.68600, 0.17505, -0.19198, 0.15088, -0.33791, -0…
## $ PC8                  &lt;dbl&gt; -0.16704, -0.15100, 0.33181, -0.71534, -1.60202, …
## $ PC9                  &lt;dbl&gt; -0.5770, 0.9726, -0.0633, 0.3675, -2.1522, -1.075…
## $ PC10                 &lt;dbl&gt; 0.5345, 1.0325, -0.1733, -0.0245, -2.1552, 2.9257…
## $ Adventure            &lt;dbl&gt; -0.464, -0.464, -0.464, -0.464, -0.464, -0.464, -…
## $ Animation            &lt;dbl&gt; -0.24, -0.24, -0.24, -0.24, -0.24, -0.24, -0.24, …
## $ Children             &lt;dbl&gt; -0.242, -0.242, -0.242, -0.242, -0.242, 4.133, -0…
## $ Comedy               &lt;dbl&gt; -0.666, -0.666, 1.500, -0.666, -0.666, -0.666, 1.…
## $ Fantasy              &lt;dbl&gt; -0.362, -0.362, -0.362, -0.362, -0.362, -0.362, -…
## $ Romance              &lt;dbl&gt; -0.458, -0.458, -0.458, -0.458, -0.458, -0.458, -…
## $ Drama                &lt;dbl&gt; 0.973, -1.028, 0.973, 0.973, 0.973, 0.973, 0.973,…
## $ Action               &lt;dbl&gt; -0.59, 1.69, -0.59, -0.59, -0.59, -0.59, -0.59, -…
## $ Crime                &lt;dbl&gt; -0.416, -0.416, -0.416, 2.401, -0.416, -0.416, -0…
## $ Thriller             &lt;dbl&gt; -0.626, 1.597, -0.626, 1.597, 1.597, -0.626, -0.6…
## $ Horror               &lt;dbl&gt; 2.85, -0.35, -0.35, -0.35, -0.35, -0.35, -0.35, -…
## $ Mystery              &lt;dbl&gt; -0.314, 3.188, -0.314, -0.314, -0.314, -0.314, -0…
## $ `Sci-Fi`             &lt;dbl&gt; -0.444, -0.444, -0.444, -0.444, 2.249, -0.444, -0…
## $ IMAX                 &lt;dbl&gt; -0.213, -0.213, -0.213, -0.213, -0.213, -0.213, -…
## $ Documentary          &lt;dbl&gt; -0.137, -0.137, -0.137, -0.137, -0.137, -0.137, -…
## $ War                  &lt;dbl&gt; -0.22, -0.22, -0.22, -0.22, -0.22, -0.22, -0.22, …
## $ Musical              &lt;dbl&gt; -0.177, -0.177, -0.177, -0.177, -0.177, -0.177, -…
## $ Western              &lt;dbl&gt; -0.127, -0.127, -0.127, -0.127, -0.127, -0.127, -…
## $ `Film-Noir`          &lt;dbl&gt; -0.123, -0.123, -0.123, -0.123, -0.123, -0.123, -…
## $ `(no genres listed)` &lt;dbl&gt; -0.0508, -0.0508, -0.0508, -0.0508, -0.0508, -0.0…</code></pre>
<pre class="r"><code>y_train_vector &lt;- train_tbl_ann$avg_rating
y_test_vector &lt;- test_tbl_ann$avg_rating</code></pre>
<p>Initially, we split the data into <em>training</em> (80%) and <em>testing</em> (20%) set and,
after this step, we pre-processed the data by <strong>standardizing</strong> the <em>numerical</em>
<em>predictive</em> variables. After adding the pre-processed data to the recipe object,
we extract the predictors and outcome variables for both train and test set. Now,
we are ready to fit the <strong>neural network</strong>.</p>
<pre class="r"><code># Creating the model_keras object
model_keras &lt;- keras_model_sequential()

# Compiling the model_keras object with the architecture defined
model_keras %&gt;% 
  
  # First hidden layer
  layer_dense(
    units              = 32, 
    kernel_initializer = &quot;uniform&quot;, 
    activation         = &quot;relu&quot;, 
    input_shape        = ncol(x_train_ann)) %&gt;% 
  
  # Dropout to prevent overfitting
  layer_dropout(rate = 0.3) %&gt;%
  
  # Second hidden layer
  layer_dense(
    units              = 64, 
    kernel_initializer = &quot;uniform&quot;, 
    activation         = &quot;tanh&quot;) %&gt;% 
  
  # Dropout to prevent overfitting
  layer_dropout(rate = 0.3) %&gt;%
  
  # Third hidden layer
  layer_dense(
    units              = 32,
    kernel_initializer = &quot;uniform&quot;, 
    activation         = &quot;tanh&quot;) %&gt;%
  
  # Dropout to prevent overfitting
  layer_dropout(rate = 0.3) %&gt;%
  
  # Output layer
  layer_dense(
    units              = 1,
    kernel_initializer = &quot;uniform&quot;, 
    activation         = &quot;relu&quot;) %&gt;% 
  
  # Compile NN
  compile(
    optimizer = optimizer_rmsprop(),
    loss      = &#39;mean_squared_error&#39;,
    metrics   = c(&#39;mean_absolute_error&#39;)
  )

#display model architecture
model_keras</code></pre>
<pre><code>## Model: &quot;sequential&quot;
## ________________________________________________________________________________
##  Layer (type)                       Output Shape                    Param #     
## ================================================================================
##  dense_3 (Dense)                    (None, 32)                      992         
##  dropout_2 (Dropout)                (None, 32)                      0           
##  dense_2 (Dense)                    (None, 64)                      2112        
##  dropout_1 (Dropout)                (None, 64)                      0           
##  dense_1 (Dense)                    (None, 32)                      2080        
##  dropout (Dropout)                  (None, 32)                      0           
##  dense (Dense)                      (None, 1)                       33          
## ================================================================================
## Total params: 5,217
## Trainable params: 5,217
## Non-trainable params: 0
## ________________________________________________________________________________</code></pre>
<pre class="r"><code># Tuning the model and keeping the accuracy metrics
history_ann &lt;- fit(
  object = model_keras,
  x = as.matrix(x_train_ann),
  y = y_train_vector,
  batch_size = 50,
  epochs = 50,
  validation_split = 0.30 #to include 30% of the data for model validation, which prevents overfitting.
)

# Printing and plotting history
print(history_ann)</code></pre>
<pre><code>## 
## Final epoch (plot to see history):
##                    loss: 0.1616
##     mean_absolute_error: 0.3216
##                val_loss: 0.09461
## val_mean_absolute_error: 0.2446</code></pre>
<pre class="r"><code>plot(history_ann)</code></pre>
<p><img src="/blogs/brexit_project_files/figure-html/Fitting%20the%20Ann-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>After tuning the model, we can now use it to predict <strong>out-of-sample</strong> data and
test its accuracy.</p>
<pre class="r"><code># Predicting using out-of-sample data
pred_test &lt;- model_keras %&gt;%
  predict(as.matrix(x_test_ann), batch_size = 50)

# Computing the RMSE for out-of-sample predictions
RMSE(pred_test, y_test_vector)</code></pre>
<pre><code>## [1] 0.298</code></pre>
<p>After tuning our Artificial Neural Network, we came up with our final
architecture and set of hyper parameters. The final Neural Networks has <strong>3</strong>
hidden layers and <em>one</em> output layer. The <em>first</em> and <em>third</em> layer of neurons
contain <strong>32</strong> neurons, whereas the second layer contains <strong>64</strong> neurons. The
activation function chosen for both the first and the last neurons is the <strong>relu</strong>
function: especially in the last layer, we want to keep an activation function
with a <em>non-vanishing gradient</em>: an activation function that does not entail
loss of information about the <em>input signal</em> due to its gradient-vanishing shape.
In addition, we decided to set a dropout percentage of <strong>30%</strong> in order to reduce
overfitting as much as we could (in fact, 30% is pretty high as a dropout
percentage). <strong>Three</strong> dropout layers have been placed after each hidden layer of
the neural network. In the end, we decided to set the optimizer as the <strong>Moving</strong>
<strong>average of the square of gradients</strong> (set by the function <em>optimizer_rmsprop()</em>),
a loss function as the mean squared error and a measure of accuracy as the mean
absolute error: the <strong>mean squared error</strong> is one of the functions that performs
most accurately with regression models.</p>
<p>In conclusion, we trained the model setting a <em>batch size</em> of <strong>50</strong> (number of
observations coming through the network at each epoch) and <strong>50</strong> <em>epochs</em> (number of
iterations of the batch through the model). Furthermore, we set the percentage of
observations left for <em>validation</em> at <strong>30%</strong>, in order to avoid overfitting as
much as possible.</p>
<p>The final <strong>out-of-sample RMSE</strong> obtained predicting ratings using the ANN is
approximately <strong>0.29</strong>.</p>
<pre class="r"><code># Tuning Linear Regression Model
ln_regression &lt;- lm(avg_rating ~ ., data=data_svm_train2)

# Calculating out-of-sample predictions for the Linear Model
lm_prediction &lt;- predict(ln_regression, data_svm_test2)

# Calculating out-of-sample RMSE for Linear Regression
RMSE(lm_prediction, data_svm_test2$avg_rating)</code></pre>
<pre><code>## [1] 0.238</code></pre>
<p>Comparing the ANN with the performance of another regression model (linear
regression model), we see that the other model actually performs better than
the ANN: the <strong>out-of-sample RMSE</strong> of the linear regression is <strong>0.2384</strong>. This is
most likely due to the fact that the relationship between the predictors and the
output variable is <em>approximately linear</em> and it is better modeled and predicted
by using a simple linear regression rather than a complex Neural Network: the
Neural Network is usually exploited for its potential to introduce <em>non-linearity</em>
in the model. In this case, though, linearity might be the solution.</p>
</div>
